# db가 testdb일떄만 꼭 실행할 것!
config:
  target: http://localhost:3000
  tls:
  rejectUnauthorized: false
  phases:
    - duration: 10
      arrivalRate: 100
scenarios:
  - name: "wordcup 조회"
    flow:
      - get:
          url: "/api/worldcup"
